### ISSUE TITLE
Make exp calculations more accurate to the original

### ISSUE THREAD

**Issue by Lekuruu** [Lekuruu/snowflake#23]
A member of the Club Penguin Avalanche server has made some research on the exp calculations, and how they actually work. Here is what they have figured out:

- The exp is awarded per enemy killed
- Enemy exp will only be awarded, after a round progresses

They have also made a table with the approximate values used:

![image](https://github.com/Lekuruu/snowflake/assets/84310095/b939725c-73ab-4296-a654-66b7a2c72995)

Each line in the table is a phase, and the percentage is awarded per enemy. The bonus round may change the overall percentage as well.

This should give us enough information to implement it.

**Comment by renanrcp** [comment]
Update: We have two exps logics (before membership and after)

Two members of Club Penguin Avalanche Server studied a lot of old videos to see what the exp logic after membership do:

### Common Battles:
- Round 1 gives you 100XP and 60 coins on win
- Round 2 gives you 200XP and 120 coins on win
- Round 3 gives you 300XP and 120 coins on win
- Bonus Round: each killed enemy gives you 75XP and 60 coins
- Wins the bonus round gives you 180 de XP and 120 coins.

### Tusk: 
The EXP and coins here uses Tusk's life as parameter

- 0% Health: gives you 2100XP and 660 coins.
- 0% > Health <= 10%: gives you 1290XP and 420 coins.
- 10% > Health <= 20%: gives you 1050XP and 300 coins.
- 20% > Health <= 30%: gives you 340XP and 180 coins.
- 30% > Health: gives you 90XP and 60 coins.

### Phases:
- Phase 1: 600XP
- Phase 2:  600XP
- Phase 3:  1130XP
- Phase 4: 1130XP
- Phase 5:  1130XP
- Phase 6:  1500XP
- Phase 7:  1500XP
- Phase 8:  2000XP
- Phase 9:  2000XP
- Phase 10:  2000XP
- Phase 11 to 24: 3000XP

**Comment by Lekuruu** [comment]
The phase is the current ninja rank I assume?

**Comment by renanrcp** [comment]
> The phase is the current ninja rank I assume?

Yes it is

**Comment by Lekuruu** [comment]
Yeah that also explains the difficulty to rank up, the higher the rank is.

![image](https://github.com/Lekuruu/snowflake/assets/84310095/9b029e7a-2564-4a7e-ae98-ee867ab13ed9)

The reward multipliers were a very hacky solution to this...

**Comment by renanrcp** [comment]
I think we can just use total value as % here

So if you are in Phase 9 with 20% and you win a bonus round with 4 enemies:
100% = 2000XP
20% = 400XP
Total earned XP = 1080

Current XP = (400 + 1080) = 1480 = 74%

**Comment by Lekuruu** [comment]
Huge thanks to JGCM, and P.H.! :tada:
