### ISSUE TITLE
Having error of loading into snow and saying im still logged in

### ISSUE THREAD

**Issue by Hoodup88** [Lekuruu/snowflake#46]
Debug error
←[38;20m[2024-07-03 19:26:36,258] - <Snowflake> ←[96mINFO: Starting world server "cjsnow_0" (7002)←[0m
←[38;20m[2024-07-03 19:26:36,259] - <Snowflake> ←[96mINFO: Registered place: "snow_lobby"←[0m
←[38;20m[2024-07-03 19:26:36,259] - <Snowflake> ←[96mINFO: Registered place: "snow_battle"←[0m
←[38;20m[2024-07-03 19:26:36,259] - <Snowflake> ←[96mINFO: Registered place: "tusk_battle"←[0m
←[38;20m[2024-07-03 19:26:36,259] - <SocketPolicyServer> ←[96mINFO: Starting policy server (843)←[0m
←[38;20m[2024-07-03 19:27:09,438] - <SocketPolicyServer> DEBUG: -> 127.0.0.1:51790←[0m
←[38;20m[2024-07-03 19:27:09,439] - <127.0.0.1> DEBUG: -> "b'<policy-file-request/>'"←[0m
←[38;20m[2024-07-03 19:27:09,439] - <127.0.0.1> DEBUG: <- "b"<cross-domain-policy><allow-access-from domain='*' to-ports='*' /></cross-domain-policy>""←[0m
←[38;20m[2024-07-03 19:27:09,439] - <127.0.0.1> DEBUG: -> Connection done←[0m

**Comment by Lekuruu** [comment]
Resolved in discord DMs.
