### ISSUE TITLE
Add "cardjitsu_snowrevive.swf" to "Setting Up Snowflake" section

### ISSUE THREAD

**Issue by renanrcp** [Lekuruu/snowflake#8]
The file `cardjitsu_snowrevive.swf` doesn't exist in the default vanilla media server provided by Solero.

Today, this file exists in this [folder](https://github.com/Lekuruu/snowflake/tree/main/.github/swf), so we can just move this file to the correct path (`media/game/mpassets/minigames/cjsnow/en_US/deploy/swf/ui/windows/`).

I think we can add this file to the [Setting Up Snowflake](https://github.com/Lekuruu/snowflake/tree/main?tab=readme-ov-file#setting-up-snowflake) section.

**Comment by renanrcp** [comment]
I'll open a PR later

**Comment by Lekuruu** [comment]
Yeah, I had asked the admins of Solero if they could add it, but no response from both of them. Feel free to make a pr!
